name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Find all Dockerfiles and Build Images
      run: |
        # Trova tutte le cartelle che contengono un Dockerfile
        for dockerfile in $(find . -type f -name 'Dockerfile'); do
          # Estrai il nome della cartella
          dir=$(dirname "$dockerfile")
          image_name="my-image-$(basename "$dir")"  # Imposta un nome per l'immagine basato sulla cartella
          
          # Costruisci l'immagine
          echo "Building image for $image_name"
          docker build -f "$dockerfile" -t "$image_name:$(date +%s)" "$dir"
        done
